const list = [
  {
    id: 1,
    title: "Mcdonalds",
    author: "McCombo de hamburguesa con pollo apanado, pepinillos con papas grandes y gaseosa grande",
    price: 15000,
    img: "https://miro.medium.com/max/1050/1*DcJz6l8JXZ7bV0SgW36MNg.jpeg",
    amount: 1,
  },
  {
    id: 2,
    title: "Qbano",
    author: "El nuevo Qbano Burger es por tiempo limitado, ¡no te quedes sin disfrutarlo!.",
    price: 27000,
    img: "https://pbs.twimg.com/media/CDDZtDZW0AAW8xy.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "Presto",
    author: "El más delicioso pan, los más frescos ingredientes y nuestra jugosa carne artesanal",
    price: 14000,
    img: "https://barranquilla.mydealstoday.co/wp-content/uploads/2017/12/perto_hamburgesas-750x750.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Papa Johns",
    author: "Pepperoni, mezcla de tres quesos, mozzarella, parmesano, romano y queso",
    price: 57000,
    img: "https://pbs.twimg.com/media/FLQQD_7WQAMN8ea.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "KFC",
    author: "6 Presas + 4 Strips + 2 Ensaladas Coleslaw Personales + 2 Papas Pequeñas + 1 Sundae Arequipe",
    price: 149000,
    img: "https://wwwhatsnew.com/wp-content/uploads/2018/12/imagen1-730x359.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Subway",
    author: "Salami rebanado estilo génova, pepperoni y jamón, añade vegetales, tu queso favorito y salsas. Llévalo combo con bebida mas acompañamiento",
    price: 10000,
    img: "https://www.subway.com/-/media/Colombia/Images/2022-JULIO/BANNER_FOOTLONG_CON_660x552.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Burger King",
    author: "En BK te invitamos a que no le pongas límites a tu antojo y agregues ¡UNA CARNE MÁS!, más queso, tocineta y pan. 🍔😱 con nuestras MEGASTACKER®️ y conviertete en un MEGASTACKER®️ Lover",
    price: 25000,
    img: "https://www.revistaneo.com/sites/default/files/2022-02/BK_Fans%20King_1.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "StarBucks",
    author: "Fresa açai refresher combinado con leche de coco para una sensación cremosa y refrescante.",
    price: 12000,
    img: "https://cdn.domestika.org/c_fit,dpr_auto,f_auto,t_base_params,w_820/v1591052883/content-items/004/768/965/CEBADA_STARBUCKS-original.png?1591052883",
    amount: 1,
  },
  {
    id: 9,
    title: "PizzaHut",
    author: "Una Pizza Mediana de 8 porciones con borde de queso (Hut Cheese) de un Ingrediente: Jamón, Tomate o Pepperoni 🍕🤤.",
    price: 80000,
    img: "https://www.latinspots.com/files/notas/Gnota_55582.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Domino's",
    author: "Una Pizza Mediana de 8 porciones con borde de queso (Hut Cheese) de un Ingrediente: Jamón, Tomate o Pepperoni 🍕🤤.",
    price: 30000,
    img: "https://cazaofertas.com.co/wp-content/uploads/2020/04/Dominos-30800-060420-1024x1024.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Wendy's",
    author: "Una jugosa pechuga de pollo, tocino ahumado de Applewood y mantequilla de arce en un bollo de croissant escamoso. Un poco dulce. Un poco sabroso. Mucho bien.",
    price: 120000,
    img: "https://interactivadigital.com/uploads/2017/04/wendys-112327.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "Kokoriko",
    author: "El tradicional y único sabor del Kokoriko Asado para compartir. 1 y 1/2 Kokoriko asado (12 presas) + veinte (20) arepas y 3 und de ají",
    price: 157000,
    img: "https://pbs.twimg.com/media/CEP47O1W8AENcqL.png",
    amount: 1,
  },
];

export default list;
